# Generated by Django 2.1.3 on 2018-12-03 18:16

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Πελάτης')),
                ('placement_datetime', models.DateTimeField(blank=True, default=orders.models.now, verbose_name='Ημερομηνία παραγγελίας')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία παράδοσης')),
                ('status', models.IntegerField(choices=[(1, 'Πρόχειρη'), (2, 'Ενεργή'), (3, 'Εγκεκριμένη'), (4, 'Εκτελείται'), (5, 'Ολοκληρωμένη')], default=0, verbose_name='Κατάσταση')),
            ],
            options={
                'verbose_name': 'Παραγγελία',
                'verbose_name_plural': 'Παραγγελίες',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Υλικό')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Ποσότητα')),
                ('x_dimension', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Διάσταση Χ')),
                ('y_dimension', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Διάσταση Υ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
