# Generated by Django 3.0.3 on 2020-02-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181203_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Στοιχείο Παραγγελίας', 'verbose_name_plural': 'Στοιχεία Παραγγελίας'},
        ),
    ]
